spring:
  application:
    name: hello-spring

  # 데이터베이스 연결을 위한 설정
  datasource:
#    url: jdbc:oracle:thin:@192.168.211.18:1521:XE
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: SPRING_BOOT
    password: 1234

  # JSP를 사용하기 위해 JSP파일들의 경로를 설정. -> common   .beans.WebConfig.java로 설정 이동함.
 # mvc:
 #   view: 
 #     prefix: /WEB-INF/views/
 #     suffix: .jsp

  servlet:
    multipart:
      # 애플리케이션이 받을 수 있는 최대 업로드 용량 (100MB)
      max-file-size: 104857600
      # 한 사용자가 업로드할 수 있는 최대 업로드 용량 (10MB)
      max-request-size: 10485760
        
#Application 전용 설정. (Spring과 관계없음.)
app:
  multipart:
    base-dir: C:\\uploadfiles #파일저장 경로 지정
    obfuscation:
      enable: true  # 난독화 여부
      hide-ext:     # 확장자도 난독화할 것인가?
        enable: true  # 확장자도 해야함




# mybatis 설정 파일의 경로 지정
myBatis:
  # mybatis-config.xml 파일의 위치를 지정.
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/ktdsuniversity/edu/hello_spring/**/dao/mapper/*Mapper.xml
