spring:
  application:
    name: hello-spring

  # 데이터베이스 연결을 위한 설정
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: TODO
    password: 1234

# mybatis 설정 파일의 경로 지정
myBatis:
  # mybatis-config.xml 파일의 위치를 지정.
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:homework/**/dao/mapper/*Mapper.xml


